# Allow rbs-inline #: comments without space after #
Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "coverage/**/*"
    - "*.gemspec"
    - "install.rb"
    - "Rakefile"

# Gem naming convention uses simple-rss.rb
Naming/FileName:
  Exclude:
    - "lib/simple-rss.rb"

# Short parameter names are acceptable for setters
Naming/MethodParameterName:
  Exclude:
    - "lib/simple-rss.rb"

# it assignment style is fine for Ruby 3.4+
Style/ItAssignment:
  Enabled: false

# Line length
Layout/LineLength:
  Max: 160
  Exclude:
    - "test/**/*"

# Security/Open is safe here - only used with File.dirname
Security/Open:
  Exclude:
    - "test/**/*"

# Bundler gem ordering not critical
Bundler/OrderedGems:
  Enabled: false

# Existing code lacks documentation, can add incrementally
Style/Documentation:
  Enabled: false

# Allow longer methods for parsing logic
Metrics/MethodLength:
  Max: 60
  Exclude:
    - "test/**/*"

# Allow higher complexity for parsing methods
Metrics/AbcSize:
  Max: 80
  Exclude:
    - "test/**/*"

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 35

# Class length for SimpleRSS
Metrics/ClassLength:
  Max: 250

# Frozen string literal is optional for this gem
Style/FrozenStringLiteralComment:
  Enabled: false

# Allow compact class/module child definitions
Style/ClassAndModuleChildren:
  Enabled: false

# Use double quotes consistently
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Allow class variables for feed_tags/item_tags
Style/ClassVars:
  Enabled: false

# Regex parsing code uses Regexp.last_match
Style/PerlBackrefs:
  Enabled: false

# Allow method_missing for item hash access
Style/MissingRespondToMissing:
  Exclude:
    - "lib/simple-rss.rb"

# Regex parsing intentionally uses nil branches for pattern matching
Lint/Void:
  Exclude:
    - "lib/simple-rss.rb"

Lint/DuplicateBranch:
  Exclude:
    - "lib/simple-rss.rb"

# class_eval used for dynamic attr_reader definition
Style/EvalWithLocation:
  Exclude:
    - "lib/simple-rss.rb"

Style/DocumentDynamicEvalDefinition:
  Enabled: false

# Regex escapes in existing code are intentional
Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

# If/unless modifier preference
Style/IfUnlessModifier:
  Enabled: false

# String concatenation in tests is fine
Style/StringConcatenation:
  Exclude:
    - "test/**/*"

# Block length for parsing
Metrics/BlockLength:
  Max: 40
  Exclude:
    - "test/**/*"
